### PR TITLE
Bazel support

### PR DESCRIPTION
**Pull request by jcking**
Add initial Bazel support to ANTLR 3.

I still need to fix the tests, as Bazel executes in a different environment, and the tests are not sure how to find the dependencies required as they run in separate sub-processes.

### CODE REVIEW

**Comment by jcking** [comment]
@parrt

**Comment by jcking** [comment]
This also fixes an infinite recursion issue in `DebugTreeAdaptor`.

**Comment by jcking** [comment]
Friendly poke. @parrt

**Comment by parrt** [comment]
Just to be pendantic, could you sign the contributors.txt? thanks!

**Comment by parrt** [comment]
Thanks!

**Pull request merged**
